import os

ENVIRONMENT_NAME = os.environ['GENEDIVE_NAME']
ENVIRONMENT_SCRIPTS_FOLDER = "/scripts"
ENVIRONMENT_DATA_FOLDER = "/data/"+ENVIRONMENT_NAME
ENVIRONMENT_SQLITE_LOCATION = ENVIRONMENT_DATA_FOLDER + "/" + ENVIRONMENT_NAME + ".sqlite"
